In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/all_kindle_review.csv')

In [ ]:
df.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [ ]:
df=df[['reviewText','rating']]

In [ ]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [ ]:
df.shape

(12000, 2)

In [ ]:
#checking the missing values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [ ]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [ ]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [ ]:
!git config --global user.name "tasnim-shamsuddin"
!git config --global user.email "tasnim.india@gmail.com"


In [ ]:
!mkdir sentiment-analysis
%cd sentiment-analysis


/content/sentiment-analysis/sentiment-analysis


In [ ]:
!git init


hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/sentiment-analysis/sentiment-analysis/.git/


In [ ]:
%%writefile README.md
# Sentiment Analysis

## Project Overview
This project performs sentiment analysis on text data (reviews) using Natural Language Processing (NLP) techniques. The goal is to classify reviews as **positive (1)** or **negative (0)** based on their rating.



## Dataset
- Reviews dataset with ratings from 1 to 5
- Ratings < 3 are labeled as 0 (negative), ratings ≥ 3 are labeled as 1 (positive)
- Dataset is mildly imbalanced (approx. 2:1)

## Data Preprocessing
- Lowercasing all text
- Removal of special characters, punctuation, emojis, URLs, HTML tags, and extra spaces
- Stopwords removal
- Lemmatization using NLTK WordNet

## Feature Engineering
Two types of vectorizations were used to convert text into numerical features:
1. **Bag of Words (CountVectorizer)** – word counts in each document
2. **TF-IDF Vectorizer** – weighted word importance based on frequency across all documents

## Models Used
- **Naive Bayes** (Gaussian/Bernoulli)

## Model Performance
| Vectorizer | Accuracy |
|------------|---------|
| Bag of Words | 0.6164 |
| TF-IDF      | 0.6169 |

**Interpretation:**
Both models achieved similar accuracy. TF-IDF slightly improved accuracy because it gives more weight to rare but informative words, while common words are down-weighted. Bag of Words is simpler and almost as effective for this dataset.

## Tools & Libraries
- Python
- pandas, numpy
- NLTK (stopwords, WordNet)
- scikit-learn (CountVectorizer, TfidfVectorizer, Naive Bayes)
- BeautifulSoup (for HTML cleaning)

## Platform
- Google Colab


Writing README.md


In [ ]:
import requests

TOKEN = "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"
USERNAME = "tasnim-shamsuddin"

url = "https://github.com/tasnim-shamsuddin/Sentiment-Analysis.git"
headers = {"Authorization": f"token {TOKEN}"}

data = {
    "name": "Sentiment-Analysis",
    "description": "Sentiment Analysis using NLP",
    "private": False
}

response = requests.post(url, json=data, headers=headers)
print(response.status_code)


200


In [ ]:
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

In [ ]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [ ]:
df['rating'].unique()

array([1, 0])

In [ ]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from bs4 import BeautifulSoup

In [ ]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', text)
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub('[^a-zA-Z0-9\s]', '', text)
    words = [w for w in text.split() if w not in stop_words]
    return " ".join(words)

df['reviewText'] = df['reviewText'].apply(clean_text)


<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2875059624.py:5: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub('[^a-zA-Z0-9\s]', '', text)


In [ ]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [ ]:
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
import re
from bs4 import BeautifulSoup

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', text)  # remove URLs
    text = BeautifulSoup(text, "html.parser").get_text()  # remove HTML
    text = re.sub('[^a-zA-Z0-9\s]', '', text)  # remove special chars
    words = [lemmatizer.lemmatize(w) for w in text.split() if w not in stop_words]  # remove stopwords + lemmatize
    return " ".join(words)

df['reviewText'] = df['reviewText'].apply(clean_text)


<>:18: SyntaxWarning: invalid escape sequence '\s'
<>:18: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-835882324.py:18: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub('[^a-zA-Z0-9\s]', '', text)  # remove special chars
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
##Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()


In [ ]:
def lemmatize_words(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [ ]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],train_size=0.20)


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X_train_cv=cv.fit_transform(X_train).toarray()
X_test_cv=cv.transform(X_test).toarray()


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()


In [ ]:
X_train_cv

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_cv=GaussianNB()
model_cv.fit(X_train_cv,y_train)

model_tfidf=GaussianNB()
model_tfidf.fit(X_train_tfidf,y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred_cv=model_cv.predict(X_test_cv)
y_pred_tfidf=model_tfidf.predict(X_test_tfidf)


In [ ]:
accuracy_bow=(accuracy_score(y_test,y_pred_cv))
accuracy_tfidf=(accuracy_score(y_test,y_pred_tfidf))

In [ ]:
accuracy_bow

0.6229166666666667

In [ ]:
accuracy_tfidf

0.624375

In [ ]:
confusion_matrix(y_test,y_pred_cv)


array([[1623, 1587],
       [2033, 4357]])

In [ ]:
confusion_matrix(y_test,y_pred_tfidf)

array([[1569, 1641],
       [1965, 4425]])

In [ ]:
!git add README.md
!git commit -m "Updated README with preprocessing, models, and accuracies"
!git branch -M main
!git remote add origin https://github.com/tasnim-shamsuddin/Sentiment-Analysis.git
!git push -u origin main


[master (root-commit) 8b1797f] Updated README with preprocessing, models, and accuracies
 1 file changed, 44 insertions(+)
 create mode 100644 README.md
fatal: could not read Username for 'https://github.com': No such device or address


In [ ]:
!cat README.md


# Sentiment Analysis

## Project Overview
This project performs sentiment analysis on text data (reviews) using Natural Language Processing (NLP) techniques. The goal is to classify reviews as **positive (1)** or **negative (0)** based on their rating.



## Dataset
- Reviews dataset with ratings from 1 to 5
- Ratings < 3 are labeled as 0 (negative), ratings ≥ 3 are labeled as 1 (positive)
- Dataset is mildly imbalanced (approx. 2:1)

## Data Preprocessing
- Lowercasing all text
- Removal of special characters, punctuation, emojis, URLs, HTML tags, and extra spaces
- Stopwords removal
- Lemmatization using NLTK WordNet

## Feature Engineering
Two types of vectorizations were used to convert text into numerical features:
1. **Bag of Words (CountVectorizer)** – word counts in each document
2. **TF-IDF Vectorizer** – weighted word importance based on frequency across all documents

## Models Used
- **Naive Bayes** (Gaussian/Bernoulli)

## Model Performance
| Vectorizer | Accuracy |
|-----

In [ ]:
!git remote add origin https://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@github.com/tasnim-shamsuddin/Sentiment-Analysis.git


error: remote origin already exists.


In [ ]:
!git push -u origin main


fatal: could not read Username for 'https://github.com': No such device or address


In [ ]:
!git add README.md
!git commit -m "Updated README with preprocessing and model accuracies"


On branch main
nothing to commit, working tree clean


In [ ]:
!git remote remove origin


In [ ]:
!git remote add origin https://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@github.com/tasnim-shamsuddin/Sentiment-Analysis.git


In [ ]:
!git branch -M main
!git push -u origin main


Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 1.08 KiB | 1.08 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/tasnim-shamsuddin/Sentiment-Analysis.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
